---
- name: MimimiBot
  hosts: all
  remote_user: root

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansistrano_allow_anonymous_stats: false
    ansistrano_deploy_to: /root
    ansistrano_keep_releases: 3
    ansistrano_deploy_via: git
    ansistrano_git_repo: git@github.com:linkita/mimimiBot.git
    ansistrano_git_branch: master
    ansistrano_git_identity_key_path: "~/.ssh/id_rsa"
    #ansistrano_after_symlink_shared_tasks_file: "{{ playbook_dir }}/deploy-hook.yml"

  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
