version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./docker/php-apache
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./:/var/www/mimimibot
            - ~/.ssh:/root/.ssh
        links:
            - db
